---
- name: Get kibana's users
  hosts: kibana
  user: ansible
  become: true

  tasks:
  - name: Cat users
    command: /bin/cat /etc/nginx/conf.d/kibana.htpasswd
    register: users


  - name: print users
    debug:
      msg: "{{ item | regex_replace('\\:.*', '') }}"
    with_items: "{{ users.stdout_lines }}"
    loop_control:
      label: "User"